name: sample application

on: [push]

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps: 
      - name: echo a string
        run: echo "Hello World"
      - name: env
        run: |
          env
          npm -v
          node -v
      - name: python command 
        run: python
        shell: python
  run-windows-command:
    runs-on: windows-latest
    steps: 
      - name: powershell
        run: |
          Get-location
      